title: "MC-SpEx: Towards Effective Speaker Extraction with Multi-Scale Interfusion and Conditional Speaker Modulation"
description: Accepted by InterSpeech 2023
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown