title: "Z-SpEx: Zero-shot Speaker Extraction with Scale Interaction and Better Combination"
description: SUBMITTED TO ICASSP 2023
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown