title: "Z-SpEx: Zero-shot Speaker Extraction with Multi-scale Interaction and Effective Cross-subnet Combination"
description: SUBMITTED TO ICASSP 2023
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown